import React, { useEffect, useState } from "react";
import { ArrowLeft, Check, CircleAlert, ExternalLink } from "lucide-react";
import { useNavigate } from "react-router";
import { useAuth } from "../../contexts/AuthContext";
import { supabase } from "../../lib/supabase";
import { evaluateProfile, getCreatorByUserId, saveSchoolEmail, updateCommissionProfile, type CreatorSummary } from "../../lib/creators";
import type { Availability, BudgetMode, WorkMode } from "../../lib/commissions";

export function CommissionProfilePage() {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [creator, setCreator] = useState<CreatorSummary | null>(null);
  const [artworkCount, setArtworkCount] = useState(0);
  const [form, setForm] = useState({ availability: 'open' as Availability, services: '', budgetMode: 'ask' as BudgetMode, budgetFrom: '', budgetTo: '', turnaroundDays: '', workMode: 'both' as WorkMode, school: '', coverImageUrl: '' });
  const [schoolEmail, setSchoolEmail] = useState('');
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');

  async function load() { if (!user) return; setLoading(true); setError(''); try { const found = await getCreatorByUserId(user.id); setCreator(found); if (found) setForm({ availability: found.availability, services: found.services.join('、'), budgetMode: found.budgetMode, budgetFrom: found.budgetFrom?.toString() ?? '', budgetTo: found.budgetTo?.toString() ?? '', turnaroundDays: found.turnaroundDays?.toString() ?? '', workMode: found.workMode, school: found.school ?? '', coverImageUrl: found.coverImageUrl ?? '' }); const { count, error: countError } = await supabase.from('artworks').select('*', { count: 'exact', head: true }).eq('artist_id', found?.artistId ?? -1).eq('status', 'published').is('deleted_at', null); if (countError) throw countError; setArtworkCount(count ?? 0); } catch (e) { setError(e instanceof Error ? e.message : '無法載入接案資料。'); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [user?.id]);
  const completeness = evaluateProfile(creator, artworkCount);
  async function save(publish?: boolean) { if (!creator) return; if (publish && !completeness.canPublish) { setError(`還缺少：${completeness.missing.join('、')}`); return; } setBusy(true); setError(''); setMessage(''); try { await updateCommissionProfile(creator.artistId, { availability: form.availability, services: form.services.split(/[、,，]/).map((x) => x.trim()).filter(Boolean), budgetMode: form.budgetMode, budgetFrom: form.budgetFrom === '' ? null : Number(form.budgetFrom), budgetTo: form.budgetTo === '' ? null : Number(form.budgetTo), turnaroundDays: form.turnaroundDays === '' ? null : Number(form.turnaroundDays), workMode: form.workMode, school: form.school.trim() || null, coverImageUrl: form.coverImageUrl.trim() || null, ...(publish === undefined ? {} : { isPublished: publish }) }); setMessage(publish === true ? '接案資料已公開。' : publish === false ? '接案資料已暫停公開。' : '接案資料已儲存。'); await load(); } catch (e) { setError(e instanceof Error ? e.message : '儲存失敗。'); } finally { setBusy(false); } }
  async function saveEmail() { if (!user) return; setBusy(true); setError(''); try { await saveSchoolEmail(user.id, schoolEmail); setMessage('信箱已儲存，但寄碼功能尚未啟用，因此不會顯示驗證徽章。'); } catch (e) { setError(e instanceof Error ? e.message : '儲存失敗。'); } finally { setBusy(false); } }

  if (loading) return <div className="mx-auto min-h-screen max-w-4xl animate-pulse px-5 pt-16"><div className="h-72 bg-white/5" /></div>;
  return <main className="mx-auto min-h-full w-full max-w-4xl px-5 pb-32 pt-10 lg:px-10 lg:pt-14">
    <button onClick={() => navigate('/profile')} className="mb-8 flex items-center gap-2 text-sm text-white/50 hover:text-white"><ArrowLeft size={17} />返回個人頁</button>
    <div className="flex flex-wrap items-end justify-between gap-5"><div><p className="mb-2 text-xs tracking-[0.18em] text-white/40">COMMISSION PROFILE</p><h1 className="text-3xl font-semibold tracking-tight">接案資料與發布</h1><p className="mt-2 text-sm text-white/45">這些資料會出現在搜尋結果與合作邀請頁。</p></div>{creator && <span className={`border px-3 py-1.5 text-xs ${creator.isPublished ? 'border-emerald-300/30 text-emerald-200' : 'border-white/15 text-white/45'}`}>{creator.isPublished ? '公開中' : '未公開'}</span>}</div>
    {error && <div role="alert" className="mt-6 border-l-2 border-red-400 bg-red-400/10 px-4 py-3 text-sm text-red-100">{error}</div>}{message && <div role="status" className="mt-6 border-l-2 border-emerald-300 bg-emerald-300/10 px-4 py-3 text-sm text-emerald-100">{message}</div>}
    {!creator ? <div className="mt-8 border border-white/10 p-6"><h2 className="font-medium">尚未建立創作者資料</h2><p className="mt-2 text-sm text-white/45">請先完成創作者註冊或聯絡管理員。</p></div> : <>
      <section className="mt-8 border border-white/10 p-5 lg:p-6"><div className="flex items-center justify-between gap-4"><div><h2 className="text-lg font-medium">發布檢查</h2><p className="mt-1 text-sm text-white/40">完成度 {completeness.percent}%</p></div><div className="text-right text-xs text-white/40">作品 {artworkCount} 件</div></div><div className="mt-5 grid gap-2 sm:grid-cols-2">{completeness.items.map((item) => <div key={item.key} className="flex items-center gap-2 text-sm"><span className={`grid h-5 w-5 place-items-center border ${item.done ? 'border-emerald-300/40 text-emerald-300' : 'border-white/15 text-white/25'}`}>{item.done ? <Check size={13} /> : <CircleAlert size={12} />}</span><span className={item.done ? 'text-white/65' : 'text-white/40'}>{item.label}{item.required && !item.done ? '（必填）' : ''}</span></div>)}</div>{completeness.missing.some((x) => x.includes('頭貼') || x.includes('自我介紹')) && <button onClick={() => navigate('/profile')} className="mt-5 flex items-center gap-2 text-sm text-white/60 underline underline-offset-4">前往編輯個人資料<ExternalLink size={14} /></button>}</section>
      <section className="mt-5 grid gap-5 border border-white/10 p-5 lg:grid-cols-2 lg:p-6"><Select label="接案狀態" value={form.availability} onChange={(v) => setForm({ ...form, availability: v as Availability })} options={[['open','開放邀請'],['limited','檔期有限'],['closed','暫不接案']]} /><Select label="合作方式" value={form.workMode} onChange={(v) => setForm({ ...form, workMode: v as WorkMode })} options={[['both','皆可'],['remote','遠端'],['in_person','面談']]} /><Field label="可承接項目"><input className="input" value={form.services} onChange={(e) => setForm({ ...form, services: e.target.value })} placeholder="平面設計、插畫、攝影" /></Field><Field label="學校或單位"><input className="input" value={form.school} onChange={(e) => setForm({ ...form, school: e.target.value })} /></Field><Select label="預算顯示" value={form.budgetMode} onChange={(v) => setForm({ ...form, budgetMode: v as BudgetMode })} options={[['ask','另議'],['from','起價'],['range','範圍']]} /><Field label="一般交件天數"><input className="input" type="number" min="1" value={form.turnaroundDays} onChange={(e) => setForm({ ...form, turnaroundDays: e.target.value })} /></Field><Field label="預算下限"><input className="input" type="number" min="0" value={form.budgetFrom} onChange={(e) => setForm({ ...form, budgetFrom: e.target.value })} /></Field><Field label="預算上限"><input className="input" type="number" min="0" value={form.budgetTo} onChange={(e) => setForm({ ...form, budgetTo: e.target.value })} /></Field><div className="lg:col-span-2"><Field label="分享封面網址（建議 1200 × 630）"><input className="input" type="url" value={form.coverImageUrl} onChange={(e) => setForm({ ...form, coverImageUrl: e.target.value })} /></Field></div></section>
      <div className="mt-5 flex flex-wrap justify-end gap-2"><button disabled={busy} onClick={() => void save()} className="border border-white/15 px-5 py-3 text-sm text-white/70 disabled:opacity-40">儲存草稿</button>{creator.isPublished ? <button disabled={busy} onClick={() => void save(false)} className="bg-white px-5 py-3 text-sm font-semibold text-black disabled:opacity-40">暫停公開</button> : <button disabled={busy || !completeness.canPublish} onClick={() => void save(true)} className="bg-white px-5 py-3 text-sm font-semibold text-black disabled:opacity-40">發布接案資料</button>}</div>
      <section className="mt-10 border-t border-white/10 pt-8"><h2 className="text-lg font-medium">成大信箱</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-white/45">目前只先儲存信箱。寄送驗證碼的 Edge Function 與寄信服務尚未啟用，因此不會顯示已驗證徽章。</p><div className="mt-4 flex max-w-xl flex-col gap-2 sm:flex-row"><input className="input flex-1" type="email" value={schoolEmail} onChange={(e) => setSchoolEmail(e.target.value)} placeholder="name@gs.ncku.edu.tw" /><button disabled={busy} onClick={() => void saveEmail()} className="border border-white/15 px-5 py-3 text-sm text-white/70 disabled:opacity-40">儲存待驗證</button></div></section>
    </>}
  </main>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm text-white/60">{label}<span className="mt-2 block">{children}</span></label>; }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: [string,string][] }) { return <Field label={label}><select value={value} onChange={(e) => onChange(e.target.value)} className="input"><>{options.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</></select></Field>; }
