-- =========================
-- ENUM TYPES
-- =========================

create type artwork_status as enum ('draft','published','archived');
create type media_type as enum ('image','video');
create type message_type as enum ('text','image','file','commission','sticker');
create type commission_status as enum ('pending','accepted','rejected','in_progress','delivered','completed');


-- =========================
-- USERS
-- id 直接對應 auth.users.id（uuid），由 trigger 自動建立
-- =========================

create table public.users (
    id         uuid primary key references auth.users(id) on delete cascade,
    email      varchar(255) unique,
    username   varchar(50) unique,
    name       varchar(100),
    birthday   timestamptz,
    avatar_url varchar(500),
    bio        text,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    deleted_at timestamptz
);

-- Trigger：用戶一完成 Supabase Auth 註冊，自動新增一筆到 public.users
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (id, email)
  values (new.id, new.email);
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();


-- =========================
-- ARTIST PROFILES
-- =========================

create table public.artist_profiles (
    id               bigint generated by default as identity primary key,
    user_id          uuid references public.users(id) on delete cascade,
    portfolio_config jsonb,
    is_verified      boolean default false,
    created_at       timestamptz default now(),
    updated_at       timestamptz default now()
);


-- =========================
-- ARTWORKS
-- =========================

create table public.artworks (
    id              bigint generated by default as identity primary key,
    artist_id       bigint references public.artist_profiles(id) on delete cascade,
    title           varchar(200),
    description     text,
    cover_image_url varchar(500),
    status          artwork_status default 'draft',
    is_for_sale     boolean default false,
    price           numeric(10,2),
    edition_type    varchar(50),
    view_count      integer default 0,
    created_at      timestamptz default now(),
    updated_at      timestamptz default now(),
    deleted_at      timestamptz
);


-- =========================
-- ARTWORK MEDIA
-- =========================

create table public.artwork_media (
    id         bigint generated by default as identity primary key,
    artwork_id bigint references public.artworks(id) on delete cascade,
    media_url  varchar(500),
    media_type media_type,
    sort_order smallint default 0
);


-- =========================
-- TAGS
-- =========================

create table public.tags (
    id       bigint generated by default as identity primary key,
    name     varchar(100) unique,
    category varchar(50)
);


-- =========================
-- ARTWORK TAGS
-- =========================

create table public.artwork_tags (
    artwork_id bigint references public.artworks(id) on delete cascade,
    tag_id     bigint references public.tags(id) on delete cascade,
    primary key (artwork_id, tag_id)
);


-- =========================
-- FOLLOWS
-- =========================

create table public.follows (
    follower_id  uuid references public.users(id) on delete cascade,
    following_id uuid references public.users(id) on delete cascade,
    created_at   timestamptz default now(),
    primary key (follower_id, following_id)
);


-- =========================
-- LIKES
-- =========================

create table public.likes (
    user_id    uuid references public.users(id) on delete cascade,
    artwork_id bigint references public.artworks(id) on delete cascade,
    created_at timestamptz default now(),
    primary key (user_id, artwork_id)
);


-- =========================
-- SAVES
-- =========================

create table public.saves (
    user_id    uuid references public.users(id) on delete cascade,
    artwork_id bigint references public.artworks(id) on delete cascade,
    created_at timestamptz default now(),
    primary key (user_id, artwork_id)
);


-- =========================
-- ARTWORK VIEWS
-- =========================

create table public.artwork_views (
    id         bigint generated by default as identity primary key,
    artwork_id bigint references public.artworks(id) on delete cascade,
    user_id    uuid references public.users(id),   -- nullable，匿名訪客也算
    created_at timestamptz default now()
);


-- =========================
-- CONVERSATIONS
-- 注意：應用層必須保證 usera_id < userb_id，避免重複建立
-- =========================

create table public.conversations (
    id              bigint generated by default as identity primary key,
    usera_id        uuid references public.users(id),
    userb_id        uuid references public.users(id),
    last_message_at timestamptz,
    created_at      timestamptz default now(),
    unique (usera_id, userb_id)
);


-- =========================
-- MESSAGES
-- =========================

create table public.messages (
    id         bigint generated by default as identity primary key,
    chat_id    bigint references public.conversations(id) on delete cascade,
    sender_id  uuid references public.users(id),
    type       message_type,
    content    jsonb,
    read_at    timestamptz,
    created_at timestamptz default now(),
    deleted_at timestamptz   -- 軟刪除，不真刪
);


-- =========================
-- COMMISSION REQUESTS
-- =========================

create table public.commission_requests (
    id             bigint generated by default as identity primary key,
    chat_id        bigint references public.conversations(id),
    client_id      uuid references public.users(id),
    artist_id      bigint references public.artist_profiles(id),
    title          varchar(200),
    description    text,
    budget         numeric(10,2),
    deadline       timestamptz,
    reference_urls jsonb default '[]',
    status         commission_status default 'pending',
    created_at     timestamptz default now(),
    updated_at     timestamptz default now()
);


-- =========================
-- TRANSACTIONS
-- MVP 階段由 Go Backend 寫入，前端只讀
-- =========================

create table public.transactions (
    id            bigint generated by default as identity primary key,
    buyer_id      uuid references public.users(id),
    artwork_id    bigint references public.artworks(id),
    commission_id bigint references public.commission_requests(id),
    amount        numeric(10,2),
    ordered_at    timestamptz,
    shipped_at    timestamptz,
    disbursed_at  timestamptz,
    received_at   timestamptz,
    refund_due_at timestamptz,
    created_at    timestamptz default now()
);


-- =========================
-- INDEXES
-- =========================

create index idx_artworks_artist        on public.artworks(artist_id);
create index idx_artwork_media_artwork  on public.artwork_media(artwork_id);
create index idx_messages_chat          on public.messages(chat_id);
create index idx_messages_sender        on public.messages(sender_id);
create index idx_views_artwork          on public.artwork_views(artwork_id);


-- =========================
-- ROW LEVEL SECURITY (RLS)
-- =========================

alter table public.users              enable row level security;
alter table public.artist_profiles    enable row level security;
alter table public.artworks           enable row level security;
alter table public.artwork_media      enable row level security;
alter table public.tags               enable row level security;
alter table public.artwork_tags       enable row level security;
alter table public.follows            enable row level security;
alter table public.likes              enable row level security;
alter table public.saves              enable row level security;
alter table public.artwork_views      enable row level security;
alter table public.conversations      enable row level security;
alter table public.messages           enable row level security;
alter table public.commission_requests enable row level security;
alter table public.transactions       enable row level security;


-- ─────────────────────────
-- users
-- ─────────────────────────

-- 所有人可以讀公開用戶資料（未被軟刪除）
create policy "users: public read"
  on public.users for select
  using (deleted_at is null);

-- 只有本人可以更新自己的資料
create policy "users: self update"
  on public.users for update
  using (auth.uid() = id);


-- ─────────────────────────
-- artist_profiles
-- ─────────────────────────

create policy "artist_profiles: public read"
  on public.artist_profiles for select
  using (true);

create policy "artist_profiles: self insert"
  on public.artist_profiles for insert
  with check (auth.uid() = user_id);

create policy "artist_profiles: self update"
  on public.artist_profiles for update
  using (auth.uid() = user_id);

create policy "artist_profiles: self delete"
  on public.artist_profiles for delete
  using (auth.uid() = user_id);


-- ─────────────────────────
-- artworks
-- 發佈的作品全公開；草稿 / 封存只有藝術家自己看得到
-- ─────────────────────────

create policy "artworks: read"
  on public.artworks for select
  using (
    (status = 'published' and deleted_at is null)
    or exists (
      select 1 from public.artist_profiles ap
      where ap.id = artworks.artist_id
        and ap.user_id = auth.uid()
    )
  );

create policy "artworks: artist insert"
  on public.artworks for insert
  with check (
    exists (
      select 1 from public.artist_profiles ap
      where ap.id = artist_id
        and ap.user_id = auth.uid()
    )
  );

create policy "artworks: artist update"
  on public.artworks for update
  using (
    exists (
      select 1 from public.artist_profiles ap
      where ap.id = artworks.artist_id
        and ap.user_id = auth.uid()
    )
  );

create policy "artworks: artist delete"
  on public.artworks for delete
  using (
    exists (
      select 1 from public.artist_profiles ap
      where ap.id = artworks.artist_id
        and ap.user_id = auth.uid()
    )
  );


-- ─────────────────────────
-- artwork_media
-- ─────────────────────────

create policy "artwork_media: public read"
  on public.artwork_media for select
  using (true);

create policy "artwork_media: artist manage"
  on public.artwork_media for all
  using (
    exists (
      select 1 from public.artworks a
      join public.artist_profiles ap on ap.id = a.artist_id
      where a.id = artwork_media.artwork_id
        and ap.user_id = auth.uid()
    )
  );


-- ─────────────────────────
-- tags（公開只讀，新增由後台管理）
-- ─────────────────────────

create policy "tags: public read"
  on public.tags for select
  using (true);


-- ─────────────────────────
-- artwork_tags
-- ─────────────────────────

create policy "artwork_tags: public read"
  on public.artwork_tags for select
  using (true);

create policy "artwork_tags: artist manage"
  on public.artwork_tags for all
  using (
    exists (
      select 1 from public.artworks a
      join public.artist_profiles ap on ap.id = a.artist_id
      where a.id = artwork_tags.artwork_id
        and ap.user_id = auth.uid()
    )
  );


-- ─────────────────────────
-- follows
-- ─────────────────────────

create policy "follows: public read"
  on public.follows for select
  using (true);

create policy "follows: self manage"
  on public.follows for all
  using (auth.uid() = follower_id);


-- ─────────────────────────
-- likes
-- ─────────────────────────

create policy "likes: public read"
  on public.likes for select
  using (true);

create policy "likes: self manage"
  on public.likes for all
  using (auth.uid() = user_id);


-- ─────────────────────────
-- saves（私人，只有自己看得到）
-- ─────────────────────────

create policy "saves: self only"
  on public.saves for all
  using (auth.uid() = user_id);


-- ─────────────────────────
-- artwork_views
-- ─────────────────────────

-- 任何人（含匿名）都可以寫入瀏覽紀錄
create policy "artwork_views: anyone insert"
  on public.artwork_views for insert
  with check (true);

-- 只有作品擁有者可以查看自己作品的瀏覽數據
create policy "artwork_views: artist read"
  on public.artwork_views for select
  using (
    exists (
      select 1 from public.artworks a
      join public.artist_profiles ap on ap.id = a.artist_id
      where a.id = artwork_views.artwork_id
        and ap.user_id = auth.uid()
    )
  );


-- ─────────────────────────
-- conversations
-- ─────────────────────────

create policy "conversations: participant read"
  on public.conversations for select
  using (auth.uid() = usera_id or auth.uid() = userb_id);

create policy "conversations: authenticated insert"
  on public.conversations for insert
  with check (auth.uid() = usera_id or auth.uid() = userb_id);

create policy "conversations: participant update"
  on public.conversations for update
  using (auth.uid() = usera_id or auth.uid() = userb_id);


-- ─────────────────────────
-- messages
-- ─────────────────────────

-- 對話參與者才能看訊息（排除軟刪除）
create policy "messages: participant read"
  on public.messages for select
  using (
    deleted_at is null
    and exists (
      select 1 from public.conversations c
      where c.id = messages.chat_id
        and (c.usera_id = auth.uid() or c.userb_id = auth.uid())
    )
  );

-- 只有對話參與者才能發訊息，且 sender_id 必須是自己
create policy "messages: sender insert"
  on public.messages for insert
  with check (
    auth.uid() = sender_id
    and exists (
      select 1 from public.conversations c
      where c.id = chat_id
        and (c.usera_id = auth.uid() or c.userb_id = auth.uid())
    )
  );

-- 只能更新自己的訊息（用於軟刪除 deleted_at）
create policy "messages: sender update"
  on public.messages for update
  using (auth.uid() = sender_id);


-- ─────────────────────────
-- commission_requests
-- ─────────────────────────

create policy "commission_requests: participant read"
  on public.commission_requests for select
  using (
    auth.uid() = client_id
    or exists (
      select 1 from public.artist_profiles ap
      where ap.id = commission_requests.artist_id
        and ap.user_id = auth.uid()
    )
  );

create policy "commission_requests: client insert"
  on public.commission_requests for insert
  with check (auth.uid() = client_id);

create policy "commission_requests: participant update"
  on public.commission_requests for update
  using (
    auth.uid() = client_id
    or exists (
      select 1 from public.artist_profiles ap
      where ap.id = commission_requests.artist_id
        and ap.user_id = auth.uid()
    )
  );


-- ─────────────────────────
-- transactions（MVP 由 backend 寫入，前端只讀）
-- ─────────────────────────

create policy "transactions: buyer read"
  on public.transactions for select
  using (auth.uid() = buyer_id);


-- =========================
-- SEED DATA
-- =========================

insert into public.tags (name, category) values
  ('Oil Painting',     'medium'),
  ('Digital Art',      'medium'),
  ('Abstract',         'style'),
  ('Portrait',         'subject'),
  ('Character Design', 'subject'),
  ('Brand Design',     'subject'),
  ('Illustration',     'medium'),
  ('3D',               'medium')
on conflict (name) do nothing;
